### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by nikkhan96** [Kotak-Neo/kotak-neo-api#117]
I got this error when I was try to install kotak neo package in windows 10.

Traceback (most recent call last):
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
    yield saved
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "C:\Users\nikun\AppData\Local\Temp\easy_install-8atjql9m\pandas-2.0.0\setup.py", line 668, in <module>
  File "C:\Users\nikun\AppData\Local\Temp\easy_install-8atjql9m\pandas-2.0.0\setup.py", line 426, in maybe_cythonize
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\Cython\Build\Dependencies.py", line 1134, in cythonize
    pool = multiprocessing.Pool(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 215, in __init__
    self._repopulate_pool()
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\context.py", line 337, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\popen_spawn_win32.py", line 72, in __init__
    with open(wfd, 'wb', closefd=True) as to_child:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 453, in _open
    if mode not in ('r', 'rt', 'rb', 'rU', 'U') and not self._ok(path):
                                                        ^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 464, in _ok
    realpath = os.path.normcase(os.path.realpath(path))
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 701, in realpath
  File "<frozen ntpath>", line 566, in normpath
TypeError: expected str, bytes or os.PathLike object, not int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\nikun\Downloads\setup.py", line 13, in <module>
    setup(
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py", line 963, in run_command
    super().run_command(command)
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\install.py", line 84, in run
    self.do_egg_install()
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\install.py", line 140, in do_egg_install
    cmd.run(show_deprecation=False)
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 442, in run
    self.easy_install(spec, not self.no_deps)
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 690, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 740, in install_item
    self.process_distribution(spec, dist, deps)
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 788, in process_distribution
    distros = WorkingSet([]).resolve(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\pkg_resources\__init__.py", line 829, in resolve
    dist = self._resolve_dist(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\pkg_resources\__init__.py", line 865, in _resolve_dist
    dist = best[req.key] = env.best_match(
                           ^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\pkg_resources\__init__.py", line 1135, in best_match
    return self.obtain(req, installer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\pkg_resources\__init__.py", line 1147, in obtain
    return installer(requirement)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 713, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 738, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 932, in install_eggs
    return self.build_and_install(setup_script, setup_base)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 1206, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\easy_install.py", line 1192, in run_setup
    run_setup(setup_script, args)
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 249, in run_setup
    with setup_context(setup_dir):
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 190, in setup_context
    with save_modules():
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 156, in save_modules
    yield saved
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "C:\Users\nikun\AppData\Local\Temp\easy_install-8atjql9m\pandas-2.0.0\setup.py", line 668, in <module>
  File "C:\Users\nikun\AppData\Local\Temp\easy_install-8atjql9m\pandas-2.0.0\setup.py", line 426, in maybe_cythonize
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\Cython\Build\Dependencies.py", line 1134, in cythonize
    pool = multiprocessing.Pool(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 215, in __init__
    self._repopulate_pool()
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\context.py", line 337, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\popen_spawn_win32.py", line 72, in __init__
    with open(wfd, 'wb', closefd=True) as to_child:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 453, in _open
    if mode not in ('r', 'rt', 'rb', 'rU', 'U') and not self._ok(path):
                                                        ^^^^^^^^^^^^^^
  File "C:\Users\nikun\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\sandbox.py", line 464, in _ok
    realpath = os.path.normcase(os.path.realpath(path))
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 701, in realpath
  File "<frozen ntpath>", line 566, in normpath
TypeError: expected str, bytes or os.PathLike object, not int

**Comment by rosevinod** [comment]
@nikkhan96  This is your computer environment problem. Try to solve it yourself. You can try virtualenv in Python.
