### ISSUE TITLE
ModuleNotFoundError: No module named 'neo_api_client' please please please help 

### ISSUE THREAD

**Issue by Jignesh108108** [Kotak-Neo/kotak-neo-api#197]
C:\Users\BAPS\PycharmProjects\KotakNeo\.venv\Scripts\python.exe C:\Users\BAPS\PycharmProjects\KotakNeo\test.py 
Traceback (most recent call last):
  File "C:\Users\BAPS\PycharmProjects\KotakNeo\test.py", line 1, in <module>
    import neo_api_client
ModuleNotFoundError: No module named 'neo_api_client'

Process finished with exit code 1
tried everything python is 3.11.4
pip install done correctly without showing any error but in pycharm above error says modulenotfound
please help

**Comment by Jignesh108108** [comment]
from neo_api_client import neoapi
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from neo_api_client import neoapi
ImportError: cannot import name 'neoapi' from 'neo_api_client' (C:\Users\BAPS\AppData\Local\Programs\Python\Python311\Lib\site-packages\neo_api_client\__init__.py)
